### ISSUE TITLE
Binary tree traversals

### ISSUE THREAD

**Issue by sudip-mondal-2002** [shivaylamba/Hacktoberfest#1045]
Want to integrate binary tree traversals, please assign me an issue

**Comment by luckysharma05** [comment]
i have added it to the c++

**Comment by yashpy** [comment]
hi shivay,

Please assign this task to me, I can fix the issue,

Thanking you,

**Comment by yashpy** [comment]
I have created Binary Tree traversals in an easy way, Plz mark this as PR closed. Do let me know if you want any changes.

Thanking you.

**Comment by yashpy** [comment]
- [x] Done with tree traversals

**Comment by 2309harshit** [comment]
Hey can you please assign this task to me. I think I can do this.
Thanks in anticipation !

**Comment by virendracarpenter** [comment]
this is a open source community here no one assign work to anyone just do want you want to work

**Comment by yashpy** [comment]
@virendracarpenter your point is absolutely correct, but Its important to ask for an assignment otherwise many people will contribute at once and moreover, the author can only take one person contribution, others code would be rejected and hence will waste their time(which they considered imp for hacktoberfest event), for non- participants its okay any one can contribute, hope you understood the point, keep that in mind.

**Comment by virendracarpenter** [comment]
> @virendracarpenter your point is absolutely correct, but Its important to ask for an assignment otherwise many people will contribute at once and moreover, the author can only take one person contribution, others code would be rejected and hence will waste their time(which they considered imp for hacktoberfest event), for non- participants its okay any one can contribute, hope you understood the point, keep that in mind.

yup bro

**Comment by losermyluckwithyou007** [comment]
Assigned me I will do it .

**Comment by rishiraj001** [comment]
Assign the issue to me i will write the code for all traversals.

**Comment by muskaanrajput14** [comment]
Please assign this task to me

**Comment by jaimoryani** [comment]
Please assign this task to me, I can write the code for all traversals in C++.
