### ISSUE TITLE
Quick Sort Algorithm in C++

### ISSUE THREAD

**Issue by Anjani27** [shivaylamba/Hacktoberfest#1488]
Hi, @shivalamba This is my first PR. I would like to contribute to this repo and add a quicksort Algorithm using C++.
Please assign this to me under Hacktoberfest 2022 .
Thanks!!

**Comment by Sumedh-byte** [comment]
Hi @shivaylamba , I am interested in resolving this issue and also making my first PR, I am also experienced in CPP language. Please assign it to me. I will deliver it within time.

**Comment by amanverma2253** [comment]
Can you please assign this issue to me ?

**Comment by sajal-19** [comment]
Kindly assign this to me . I have a very efficient solution for this algorithm.

**Comment by janvichoudhary08** [comment]
hey please  assign me  this issue as a part of  hacktoberfest.

**Comment by shivani736** [comment]
can u assign me this issue

**Comment by RaunakJain21** [comment]
hey please assign me this issue

**Comment by subhasis003** [comment]
Hi , can you please assign this issue to me ? I am a beginner in Hacktoberfest & it would be better if you assign this issue to me.

**Comment by jalajsc** [comment]
hi, please assign this issue to me. Quick sort is a divide and conquers algorithm I can add this.😊😊

**Comment by annihilon** [comment]
Hi @shivaylamba , I am interested in DSA, can u assign me this issue, I can do it in the shortest way.
