### ISSUE TITLE
Binary Search Leetcode problems

### ISSUE THREAD

**Issue by anantnipunge** [shivaylamba/Hacktoberfest#1915]

**Comment by anantnipunge** [comment]
please assign this issue to me? willing to contribute in your project.

**Comment by Prasad0535** [comment]
can you assign me the issue I will add program  of binary serach  problems

**Comment by Avy2808** [comment]
Please assign me this issue, I would add the code of binary search problem.

**Comment by sahukartikey** [comment]
Can you assign this issue to me, I can add the code of binary search problem.

**Comment by nshk28** [comment]
hey! could you please assign me this issue?
