### ISSUE TITLE
LeetCode 75 Solutions

### ISSUE THREAD

**Issue by Shrimad-Bhagwat** [shivaylamba/Hacktoberfest#2125]
## Add your solutions for the LeetCode 75 🎯 plan.

🧑‍💻Create seperate folders for different languages and upload your best solution with explanation.

LeetCode75
-  C++
-  Java

Link🔗 : https://leetcode.com/studyplan/leetcode-75/

**Comment by Shrimad-Bhagwat** [comment]
Hi @shivaylamba, I would like to work on this issue. Can you please assign this task to me.

**Comment by rishiraj88** [comment]
@Shrimad-Bhagwat , have you solved any of the problems in that LeetCode list?
Have you shared or would you like to share links to those under this "issue" for us all?
