### ISSUE TITLE
Tic Tac Toe Game (Python)

### ISSUE THREAD

**Issue by Gurpreet0022** [shivaylamba/Hacktoberfest#2340]
Hey Shivay,

Could you please assign me the issue mentioned above with the hacktoberfest and hacktoberfest-accepted labels? I am new to open source contributions and eager to start my journey in this space. Any help or guidance would be greatly appreciated. Thanks in advance!

**Comment by tri0n0** [comment]
Hey there, I have added the file for the tic-tac-toe game in the Python folder, you can check it out.

**Comment by AnubhavSingh99** [comment]
\assign
