### ISSUE TITLE
Add HacktoberFest 2020 Topic

### ISSUE THREAD

**Issue by aayushgarg-03** [shivaylamba/Hacktoberfest#590]
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by shivaylamba** [comment]
@aayushgarg-03 the label is added. Thankyou!

**Comment by aayushgarg-03** [comment]
It still says that the repository is ineligible

**Comment by kvv1618** [comment]
The repository is ineligible for hackertober 2020.
Please add the "hacktoberfest" topic to this repository repository
