### ISSUE TITLE
The repository is ineligible for Hacktoberfest 2020

### ISSUE THREAD

**Issue by kvv1618** [shivaylamba/Hacktoberfest#627]
"Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate."

Please add the "hacktoberfest" topic to this repository

**Comment by DeltaCoderr** [comment]
Yeah, that said. Hacktoberfest has included some new rules. You should read them just in case, https://hacktoberfest.digitalocean.com/hacktoberfest-update

* Basically just add the Hacktoberfest topic to the repo, and Assign a topic of `hacktoberfest` to the PR. Pull requests to those repos must either be merged, approved or labelled as `hacktoberfest-accepted` to count

**Comment by shivaylamba** [comment]
Alright @kvv1618
