### ISSUE TITLE
The repository is ineligible for Hacktoberfest 2020

### ISSUE THREAD

**Issue by PedroCisnerosSantana** [shivaylamba/Hacktoberfest#640]
Still having the same issue

 Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate

**Comment by shivaylamba** [comment]
I have contacted Hacktoberfest Digital ocean Email and I will update once I get a response
